---
- name: Install docker-cli
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    set -Eeo pipefail
    set -x
    
    apt update
    apt install ca-certificates curl gnupg lsb-release
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) \
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt update
    apt install -y --no-install-recommends docker-ce-cli docker-compose-plugin
    
  notify:
    - Docker-cli installation is done