galaxy_info:
  author: Daiki Hayashi
  description: Install kubectl command.
  company: Human Dataware Lab. Co., Ltd.
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
  - name: Ubuntu
    versions:
      - focal
      - jammy
  galaxy_tags: []
dependencies:
  - role: sudo
